# Generated by Django 3.0.6 on 2020-06-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200623_0611'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(default='asa-asfg', editable=False, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
